version: '3'

services:
  web:
    image: "${DOCKER_IMAGE}"  # Use environment variable for image name
    ports:
      - "80:80"
    environment:
      - NODE_ENV=${NODE_ENV}  # Use environment variable for NODE_ENV
    command: ["npm", "start"]
