version: '3'

services:
  web:  # Ensure this matches the Jenkins pipeline service name
    image: "${DOCKER_IMAGE}"  # Dynamically set image name from .env file
    ports:
      - "80:80"
    environment:
      - NODE_ENV=${NODE_ENV}  # Set environment mode dynamically
    command: ["npm", "start"]
